services:
  influxdb:
    image: influxdb:2.7.6 
    container_name: influxdb_service
    env_file:
      - .env
    ports:
      - "8086:8086" # Puerto para la API de InfluxDB y UI
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PWD}
      - DOCKER_INFLUXDB_INIT_ORG=cibergu
      - DOCKER_INFLUXDB_INIT_BUCKET=airquality
      - DOCKER_INFLUXDB_INIT_RETENTION_PERIOD=15d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - zsh-supremacists

  telegraf:
    image: telegraf:1.29 
    container_name: telegraf_service
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro 
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
    environment:
      # Pasamos el token de InfluxDB a Telegraf como variable de entorno
      - INFLUX_TOKEN=my-super-secret-admin-token
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=my-bucket
      
    networks:
      - zsh-supremacists

  grafana:
    image: grafana/grafana-oss:10.4.2 
    container_name: grafana_service
    env_file:
      - .env
    ports:
      - "3000:3000" 
    volumes:
      - ./grafana-data:/var/lib/grafana 
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GR_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GR_ADMIN_PWD}
    networks:
      - zsh-supremacists

networks:
  zsh-supremacists:
    external: true