services:
  influxdb:
    image: influxdb:2.7.6 
    container_name: influxdb_service
    user: "${UID}:${GID}"
    env_file:
      - .env
    expose:
      - "8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PWD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION_PERIOD=15d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - servicios_zsh-supremacists

  telegraf:
    image: telegraf:1.29 
    user: "${UID}:${GID}"
    container_name: telegraf_service
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    expose:
      - "8080"
    depends_on:
      - influxdb
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}  
    networks:
      servicios_zsh-supremacists:
        ipv4_address: 172.22.0.5

  grafana:
    build: 
      context: .
      dockerfile: grafana.dockerfile
    user: "${UID}:${GID}"
    container_name: grafana_service
    env_file:
      - .env
    expose:
      - "3000"
    volumes:
      - ./grafana-data:/var/lib/grafana 
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GR_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GR_ADMIN_PWD}
      - GF_INSTALL_PLUGINS=grafana-image-renderer
    networks:
      - servicios_zsh-supremacists
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager-fair
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8801:80'
      - '8543:443'
      - '8170:81'
    environment:
      - DB_MYSQL_PASSWORD:${MYSQL_PWD}
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - servicios_zsh-supremacists

networks:
  servicios_zsh-supremacists:
    external: true
  