services:
  influxdb:
    image: influxdb:2.7.6 
    container_name: influxdb_service
    user: "${UID}:${GID}"
    env_file:
      - .env
    ports:
      - "8086:8086" # Puerto para la API de InfluxDB y UI
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PWD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION_PERIOD=15d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - servicios_zsh-supremacists

  telegraf:
    image: telegraf:1.29 
    user: "${UID}:${GID}"
    container_name: telegraf_service
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}  
    networks:
      servicios_zsh-supremacists:
        ipv4_address: 172.22.0.5

  grafana:
    image: grafana/grafana-oss:10.4.2 
    user: "${UID}:${GID}"
    container_name: grafana_service
    env_file:
      - .env
    ports:
      - "3000:3000" 
    volumes:
      - ./grafana-data:/var/lib/grafana 
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GR_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GR_ADMIN_PWD}
    networks:
      - servicios_zsh-supremacists

networks:
  servicios_zsh-supremacists:
    external: true