services:
  ubuntu-tomas: 
    build:
      context: . 
      dockerfile: ubuntu.dockerfile 
    container_name: ubuntu-tomas 
    
    volumes:
      - ./scripts/:/app/
    #command: ["zsh", "/app/script.zsh"]
      
    restart: unless-stopped
    stdin_open: true
    tty: true 
    networks:
      - zsh-supremacists

networks:
  zsh-supremacists:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: "172.22.0.0/24"
          gateway: "172.22.0.1"